<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace TmdbProxy\DataSource\User;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(100) NOT NULL
 * @property mixed $email varchar(200) NOT NULL
 * @property mixed $password varchar(200)
 * @property mixed $created datetime
 * @property mixed $modified datetime
 */
trait UserFields
{
}
